In [1]:
import numpy as np
import math
import scipy as sp
from reader import *

In [2]:
df = pd.read_csv("coneb1.geo")
geo = np.vstack([list(df.columns), df.to_numpy()])
dim = np.array([collate_3d(i, geo) for i in range(len(geo))])
print(dim)

[[-3.36447090e-01 -1.64537400e-03 -1.00119792e-01]
 [-3.36459994e-01  2.89579984e-17 -1.00000001e-01]
 [-3.36437106e-01 -3.29076429e-03 -1.00000001e-01]
 ...
 [-4.08889502e-01  8.62837117e-03 -4.97799993e-01]
 [-4.08980072e-01  4.30042762e-03 -4.97799993e-01]
 [-4.09009993e-01 -3.78428116e-17 -4.97799993e-01]]


In [9]:
unique = []
unique.append(dim[0][2])
for i in range(len(dim)):
    if 2 <= len(unique):
        break
    if dim[i][2] in unique:
        continue
    else:
        unique.append(dim[i][2])

In [11]:
dim2 = np.array([collate_2d(i, geo) for i in range(len(geo))])
print(dim2)

[[-3.36447090e-01 -1.64537400e-03]
 [-3.36459994e-01  2.89579984e-17]
 [-3.36437106e-01 -3.29076429e-03]
 ...
 [-4.08889502e-01  8.62837117e-03]
 [-4.08980072e-01  4.30042762e-03]
 [-4.09009993e-01 -3.78428116e-17]]
